const data = [
    { option: "0", style: { backgroundColor: "green", textColor: "yellow" } },
    { option: "28", style: { backgroundColor: "black", textColor: "white" } },
    { option: "9", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "26", style: { backgroundColor: "black", textColor: "white" } },
    { option: "30", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "11", style: { backgroundColor: "black", textColor: "white" } },
    { option: "7", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "20", style: { backgroundColor: "black", textColor: "white" } },
    { option: "32", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "17", style: { backgroundColor: "black", textColor: "white" } },
    { option: "5", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "22", style: { backgroundColor: "black", textColor: "white" } },
    { option: "34", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "15", style: { backgroundColor: "black", textColor: "white" } },
    { option: "3", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "24", style: { backgroundColor: "black", textColor: "white" } },
    { option: "36", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "13", style: { backgroundColor: "black", textColor: "white" } },
    { option: "1", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "00", style: { backgroundColor: "green", textColor: "white" } },
    { option: "27", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "10", style: { backgroundColor: "black", textColor: "white" } },
    { option: "25", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "29", style: { backgroundColor: "black", textColor: "white" } },
    { option: "12", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "8", style: { backgroundColor: "black", textColor: "white" } },
    { option: "19", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "31", style: { backgroundColor: "black", textColor: "white" } },
    { option: "18", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "6", style: { backgroundColor: "black", textColor: "white" } },
    { option: "21", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "33", style: { backgroundColor: "black", textColor: "white" } },
    { option: "16", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "4", style: { backgroundColor: "black", textColor: "white" } },
    { option: "23", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "35", style: { backgroundColor: "black", textColor: "white" } },
    { option: "14", style: { backgroundColor: "red", textColor: "yellow" } },
    { option: "2", style: { backgroundColor: "black", textColor: "white" } }
];

export default data